### PR TITLE
Refactored EPDQ gem

### PR DESCRIPTION
**Pull request by Firefishy**
Refactored EPDQ.

### CODE REVIEW

**Comment by Firefishy** [comment]
@alkesh @andypearson This code was left dangling. Creating an upstream PR so that others can see ;-)

**Comment by andypearson** [comment]
I'm sure I had a reason for doing this but I sure don't remember what that reason is now :)

**Comment by alkesh** [comment]
It was refactored, because we wanted to be able to update the EPDQ settings without restarting the Rails app using this gem.
Previously, the settings were class variables, set in an initializer.
This change made the settings parameters when creating an EPDQ client instance, so they can be more easily changed.

**Comment by andypearson** [comment]
@alkesh oh yeah! Good remembering!

**Comment by npc-adrian** [comment]
Hi Everyone,

I recently took over as Head Of Engineering at Newspaper Club and none of the technical staff from 2013 when this gem was last changed are with the company any more so I'm afraid I don't know the history of this repo.  In fact, I wasn't ever aware of it until the this PR came because we don't use ePDQ any more (if we ever did, indeed).

Unfortunately, this means we can't support for this repo/gem any more and it needs a new owner and home.  I'm happy to help transfer ownership if someone were to volunteer to take it on.

@tomtaylor is this something you can help with?

Many Thanks

Adrian

**Comment by tomtaylor** [comment]
Hi folks, @npc-adrian  - I wrote some of this, but it never ended up in production, if I remember correctly. If someone else wants control of the gem, I'm happy to transfer it.

**Comment by Firefishy** [comment]
While you are all here @alext @andypearson @alkesh @npc-adrian @tomtaylor OK with the code being licensed under standard MIT license? Currently there is no indication of license.

**Comment by tomtaylor** [comment]
Yep, I wrote *most* of it, and I am.

**Comment by alext** [comment]
Fine by me.

**Comment by tomtaylor** [comment]
@Firefishy do you want ownership of the gem and repo?

**Comment by Firefishy** [comment]
@tomtaylor sure, works for me. I am ops, not a developer, but the forked version we have is in active production by We Are Friday.

**Pull request closed without merging**
